security:
  enable_authenticator_manager: true
  providers:
      mongo_provider:
          mongodb:
              class: App\Document\DashUser
              property: discordId
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: mongo_provider
      custom_authenticators:
        - App\Security\DiscordAuthenticator
      logout:
        path: logout
  role_hierarchy:
    ROLE_ADMIN: [ROLE_STAFF]
    ROLE_STAFF: [ROLE_USER]
    ROLE_USER: [ROLE_USER]
