doctrine_mongodb:
    auto_generate_proxy_classes: false
    auto_generate_hydrator_classes: false

framework:
    cache:
        pools:
            doctrine_mongodb.system_cache_pool:
                adapter: cache.system
